CREATE TABLE [dbo].[Autoria](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AutorId] [int] NOT NULL,
	[LivroId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Autoria]  WITH CHECK ADD FOREIGN KEY([AutorId])
REFERENCES [dbo].[Autor] ([Id])
GO
ALTER TABLE [dbo].[Autoria]  WITH CHECK ADD FOREIGN KEY([LivroId])
REFERENCES [dbo].[Livro] ([Id])